@startuml

class PC {
    -placa : Placa
}

class Placa {
    -modulosRAM : List<RAM>
    -maxModulos : int
    -maxRAM : int
    -maxMhz : int
}

class RAM {
    -capacidad : int
    -mhz : int
}

PC --o Placa
Placa "1" --o "*" RAM

@enduml