@startuml
class Coche {
    - String matrícula
    - float depósito
    - float capacidad
    - boolean encendido

    + C/G/S()
    + cargarCombustible(float litros) : boolean
    + llenarDepósito() : float
    + encender()
    + apagar()
}
class Surtidor {
    - float capacidad
    - float litrosActuales
    - float precioLitro
    - float litrosSurtidosCoche

    + calcularImporte() : float
    + surtirLitros(litros, coche) : float
    + llenarDepósito(coche) : float
    + surtirPorPrecio(importe, coche) : float
    + rellenarSurtidor() : float
    + rellenarSurtidor(litros) : float
}
Surtidor -u- Coche

@enduml