@startuml
class BuscaminasConsola {
    -tablero : Tablero

    +destapar() : boolean
    +mostrarTablero() : void
    +terminarJuego() : void
}

class Tablero {
    -celdas : Celda[][]

    +crearTablero() : void
    +destapar(fila : int, columna : int) : boolean
    +calcularResultado() : boolean
    +getMinasAlrededor(fila : int, columna : int)
}

class Celda {
    -mina : boolean
    -minasAlrededor : byte
    -destapada : boolean

    +destapar() : boolean
    +getMinasAlrededor() : byte
    +setMinasAlrededor() : void
    +isMina() : boolean
    +colocarMina() : void
}

Tablero "1" *-- "n" Celda
BuscaminasConsola "1" *-- "1" Tablero

@enduml