@startuml
class BuscaminasConsola {
    -tablero : Tablero

    +BuscaminasConsola()
    -destapar() : boolean
    -mostrarTablero() : void
    -calcularResultado() : boolean
    -elegirDificultad() : void
    +iniciarPartida() : void
}

class Tablero {
    + {static} DIFICULTAD_FACIL : int
    + {static} DIFICULTAD_MEDIA : int
    + {static} DIFICULTAD_DIFICIL : int
    + {static} DIFICULTAD_EXPERTO : int
    ---
    -celdas : Celda[][]
    -coordenadasAlrededor : Set<Point>
    -casillasDestapadas : int
    -rows : int
    -columns : int
    -numeroMinas : int
    -minaExplotada : boolean
    ---
    +Tablero()
    +crearTablero() : void
    +destapar(fila : int, columna : int) : boolean
    +calcularResultado() : boolean
    -calcularMinasAlrededor(fila : int, columna : int)
    +toString() : String
    +destaparMinas() : void
}

class Celda {
    -mina : boolean
    -minasAlrededor : byte
    -destapada : boolean

    +Celda()
    +destapar() : boolean
    +getMinasAlrededor() : byte
    +setMinasAlrededor() : void
    +isMina() : boolean
    +colocarMina() : void
    +isDestapada() : boolean
    +toString() : String
}

Tablero "1" *-- "n" Celda
BuscaminasConsola "1" *-- "1" Tablero

@enduml